spring:
  application:
    name: pixel-starships-crew
  profiles:
    active: "local"

info:
  app:
    name: Pixel Starships Crew API
    description:
    version: 1.0.0

server:
  servlet:
    context-path: /pixel-starships

application:

---

spring:
  profiles: local

application:
  mongo:
    host: localhost
    port: 27017
    databaseName: pixelStarshipsDb

---

spring:
  profiles: dev

---

spring:
  profiles: qa

---

spring:
  profiles: prod

